# -*- coding: utf-8 -*-
"""Ceaser_Cipher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-LKTswonGx2vrgew-s9zzRwoPmOLxSwy
"""

import string
alpha=list(string.ascii_lowercase)
print(alpha)

word=input("Enter your word=")
shift=int(input("Enter your shift="))

name=""
def encoder(alpha,name):
  for i in word:
    index=(alpha.index(i)+shift) % 26
    name+=alpha[index]
  print(f"Your encoded message is {name}")
  return name
encoded_name = encoder(alpha,name)

decoded_name = ""

def decoder(decoded_name, alpha):
  for d in encoded_name:
    decode = (alpha.index(d)-shift) % 26
    decoded_name += alpha[decode]
  print(f"Your decoded name is {decoded_name}")
  return decoded_name

decoder(decoded_name, alpha)

# # Separate Input Based Decoder

# letters = list(string.ascii_lowercase)
# print(letters)

# code = input("Please enter the code = ")
# neg_shift = int(input("Plz enter the negative shift value = "))

# msg = ""
# def decoder_msg(letters,msg):
#   for d in code:
#     decoder = letters.index(d)-neg_shift
#     msg += letters[decoder]
#   print(f"Your Decoded Msg Is: {msg}")
#   return msg
# decoder_msg(letters,msg)



